author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/v3/encrypt'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        # 任务类型（收集：0、签到：1、查寝2）
        type: 1
        # 学校名称
        schoolName: '安徽城市管理职业学院'
        # 账号
        username: '21312273'
        # 密码
        password: 'xuyang0226..'
        # 定位位置信息
        address: '合肥市蜀山区耕耘路158号'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '1181010780@qq.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 117.240772
        #经纬度信息
        lat: 31.767152
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
        #photo 签到照片，不需要可不填，或者直接删除
        photo: qiandao.jpg   #将签到照片放到根目录photo文件夹，支持多张照片随机签到，若不用照片可忽略！
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 0
        # 表单信息
        forms:
            - form:
                  title: 您今日午检体温是否正常
                  value: 是
            - form:
                  title: 您今日午检具体体温是
                  value: 其它
                  other: 36.4


  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        # 任务类型（收集：0、签到：1、查寝2）
        type: 1
        # 学校名称
        schoolName: '安徽城市管理职业学院'
        # 账号
        username: '21112014'
        # 密码
        password: '20020604'
        # 定位位置信息
        address: '合肥市瑶海区淮海大道300号'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: '1181010780@qq.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 117.397655
        #经纬度信息
        lat: 31.936112
        #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
        #photo 签到照片，不需要可不填，或者直接删除
        photo: qiandao.jpg   #将签到照片放到根目录photo文件夹，支持多张照片随机签到，若不用照片可忽略！
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 0
        # 表单信息
        forms:
            - form:
                  title: 您今日午检体温是否正常
                  value: 是
            - form:
                  title: 您今日午检具体体温是
                  value: 其它
                  other: 36.4
