author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/v3/encrypt'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
        # 任务类型（收集：0、签到：1、查寝2）
        type: 0
        # 学校名称
        schoolName: '安徽城市管理职业学院'
        # 账号
        username: '21312273'
        # 密码
        password: 'xuyang0226'
        # 定位位置信息
        address: '安徽省蒙城县城关镇玖龙皇家花园'
        #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
        sendKey: ''
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # 经纬度信息
        lon: 116.534937
        #经纬度信息
        lat: 33.24545
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
            - form:
                  title: 今日具体所在地
                  value: 安徽省/亳州市/蒙城县
            - form:
                  title: 今天你的体温是多少
                  value: 37.2℃及以下
            - form:
                  title: 今天你的健康状况是
                  value: 健康
            - form:
                  title: 近14天你或你的共同居住人是否有疫情中，高风险区域人员接触史
                  value: 否
            - form:
                  title: 近14天你或你的共同居住人是否和确诊，疑似病人接触过
                  value: 否
            - form:
                  title: 近14天你或你的共同居住人是否是确诊，疑似病例
                  value: 否
            - form:
                  title: 你或你的共同居住人目前是否被医学隔离
                  value: 否
            - form:
                  title: 今天你当地的健康码颜色是
                  value: 绿色
            - form:
                  title: 本人承诺
                  value: 是
